# Generated by Django 5.0.6 on 2024-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motivation", "0002_achievement_conditions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserachievement",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
