# Generated by Django 5.0.6 on 2024-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motivation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="conditions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalachievement",
            name="conditions",
            field=models.JSONField(default=dict),
        ),
    ]
